version: "3"

services:
   web:
      build: .
      volumes:
         - .:/code
      expose:
         - 8000
      links:
         - redis:redis
      command:
         - /bin/bash
         - -c
         - |
            cd /code/project
            daphne -b 0.0.0.0 -p 8000 project.asgi:application
   redis:
      image: redis
      expose:
         - 6379
   nginx:
      restart: always
      build: ./nginx/
      depends_on:
         - web
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./project/static:/static
         - ./project/media:/media
      links:
         - web:web
