# Generated by Django 3.0.4 on 2020-03-17 21:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
