# Generated by Django 3.0.4 on 2020-03-17 21:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0002_auto_20200317_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
