# Generated by Django 3.0.4 on 2020-03-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0003_auto_20200317_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='denconnectionmodel',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
