# Generated by Django 3.0.4 on 2020-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0004_denconnectionmodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denmodel',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
